export const MAXIMUM_USERS_FOR_ONE_ROOM = 5;
export const MILLISECONDS_TIMER_BEFORE_START_GAME = 10;
export const SECONDS_TIMER_BEFORE_START_GAME = MILLISECONDS_TIMER_BEFORE_START_GAME * 1000;
export const MILLISECONDS_FOR_GAME = 140;
export const SECONDS_FOR_GAME = MILLISECONDS_FOR_GAME * 1000;
